# Generated by Django 4.2.6 on 2024-05-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motonave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_serviciosHistorial', models.PositiveIntegerField(default=0)),
                ('cantidad_serviciosActual', models.PositiveIntegerField(default=0)),
                ('comentarioActual', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_nominacion', models.DateTimeField(auto_now_add=True)),
                ('cantBodegas', models.CharField(max_length=50)),
                ('numero_viaje', models.IntegerField(default=0)),
                ('estado_servicio', models.CharField(choices=[('Nominado', 'Nominado'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Disponible', 'Disponible')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('litros_ingreso', models.BigIntegerField()),
                ('numero_factura', models.BigIntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
                ('tipo_quimico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('numero_motor', models.CharField(max_length=100, unique=True)),
                ('numero_chasis', models.CharField(max_length=100, unique=True)),
                ('cilindrada', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('primer_ingreso', models.DateField()),
                ('patente', models.CharField(max_length=6, unique=True)),
                ('fecha_permiso_circulacion', models.DateField()),
                ('fecha_soap', models.DateField()),
                ('fecha_revision_tecnica', models.DateField()),
                ('seguro_nombre', models.CharField(max_length=100)),
                ('seguro_poliza', models.BigIntegerField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(choices=[('Operario', 'Operario'), ('Jefe de Cuadrilla', 'Jefe de Cuadrilla'), ('Supervisor', 'Supervisor')], default='Operario', max_length=20)),
                ('conductor', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True)),
                ('tipo_licencia', models.CharField(blank=True, choices=[('', ''), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
                ('especialidades', models.ManyToManyField(to='erp.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='FichaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('fecha_inicioFaena', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_delServicio', models.CharField(choices=[('Nominado', 'Nominado'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Disponible', 'Disponible')], default='Disponible', max_length=20)),
                ('motonave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_servicio', to='erp.motonave')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(default='Nombre Predeterminado', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
