# Generated by Django 4.2.6 on 2024-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_motonave'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motonave',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motonave',
            name='responsable',
            field=models.CharField(default='Sin responsable', max_length=100),
        ),
    ]
