# Generated by Django 4.2.6 on 2024-05-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_motonave_agencia_motonave_armador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaservicio',
            name='personal_nominado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_servicio', to='erp.personal'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='quimico_nominado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_servicio', to='erp.quimico'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='vario_nominado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_servicio', to='erp.vario'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='vehiculo_nominado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_servicio', to='erp.vehiculo'),
        ),
    ]
