# Generated by Django 4.2.6 on 2024-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_motonave_descripcion_motonave_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='estado_servicio',
            field=models.CharField(choices=[('Nominado', 'Nominado'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado'), ('Disponible', 'Disponible')], default='Disponible', max_length=20),
        ),
    ]
