# Generated by Django 4.2.6 on 2024-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_fichaservicio_personal_nominado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaservicio',
            name='quimico_nominado',
        ),
        migrations.RemoveField(
            model_name='fichaservicio',
            name='vario_nominado',
        ),
        migrations.RemoveField(
            model_name='fichaservicio',
            name='vehiculo_nominado',
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='quimicos_nominados',
            field=models.ManyToManyField(blank=True, related_name='fichas_servicio', to='erp.quimico'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='varios_nominados',
            field=models.ManyToManyField(blank=True, related_name='fichas_servicio', to='erp.vario'),
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='vehiculos_nominados',
            field=models.ManyToManyField(blank=True, related_name='fichas_servicio', to='erp.vehiculo'),
        ),
        migrations.RemoveField(
            model_name='fichaservicio',
            name='personal_nominado',
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='personal_nominado',
            field=models.ManyToManyField(blank=True, related_name='fichas_servicio', to='erp.personal'),
        ),
    ]
