# Generated by Django 4.2.6 on 2024-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_motonave_estado_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='viaje',
            field=models.IntegerField(default=0),
        ),
    ]
