# Generated by Django 4.2.6 on 2024-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_motonave_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(choices=[('Operario', 'Operario'), ('Jefe de Cuadrilla', 'Jefe de Cuadrilla'), ('Supervisor', 'Supervisor')], default='Operario', max_length=20)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
            ],
        ),
    ]
