# Generated by Django 4.2.6 on 2024-05-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_fichaservicio_arriendo_bomba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichaservicio',
            old_name='hospedaje_desayuno',
            new_name='hospedaje',
        ),
        migrations.RenameField(
            model_name='fichaservicio',
            old_name='lancha_grua',
            new_name='lancha',
        ),
        migrations.AddField(
            model_name='fichaservicio',
            name='grua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
