# Generated by Django 4.2.6 on 2024-06-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_rename_hospedaje_desayuno_fichaservicio_hospedaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaservicio',
            name='fecha_inicioFaena',
            field=models.DateField(blank=True, null=True),
        ),
    ]
