# Generated by Django 4.2.6 on 2024-04-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motonave',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='motonave',
            name='viaje',
        ),
    ]
