# Generated by Django 4.2.6 on 2024-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_remove_motonave_responsable_remove_motonave_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='cantidad_servicios',
            field=models.IntegerField(default=0),
        ),
    ]
