# Generated by Django 4.2.6 on 2024-06-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_fichaservicio_fecha_iniciofaena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(default='sin_archivo.txt', upload_to='documentos/')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('seccion', models.CharField(choices=[('Personal', 'Personal'), ('Inventario', 'Inventario'), ('Servicio', 'Servicio'), ('Otros', 'Otros')], max_length=20)),
                ('sub_seccion', models.CharField(blank=True, choices=[('Contrato', 'Contrato'), ('Ficha de Ingreso', 'Ficha de Ingreso'), ('Boletas', 'Boletas'), ('Facturas', 'Facturas'), ('Reportes', 'Reportes'), ('Fichas', 'Fichas')], max_length=20, null=True)),
                ('ficha_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.fichaservicio')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.personal')),
            ],
        ),
    ]
