# Generated by Django 4.2.6 on 2024-04-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_motonave_cantidad_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motonave_nombre', models.CharField(max_length=100)),
                ('numero_viaje', models.IntegerField()),
                ('procedencia', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('armador', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=100)),
                ('arribo', models.DateField()),
                ('hospedaje_desayuno', models.BooleanField()),
                ('lancha_grua', models.BooleanField()),
                ('cantidad_bodegas', models.IntegerField()),
                ('arriendo_bomba', models.BooleanField()),
                ('navegacion', models.BooleanField()),
                ('prox_puerto', models.CharField(max_length=100)),
                ('loi', models.CharField(max_length=100)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
