# Generated by Django 4.2.6 on 2024-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaservicio',
            name='conductores_vinculados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
