# Generated by Django 4.2.6 on 2024-04-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_fichaservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motonave',
            name='cantidad_servicios',
        ),
    ]
