# Generated by Django 4.2.6 on 2024-06-14 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_fichaservicio_conductores_vinculados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_servicio', models.IntegerField()),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('fecha_inicio_faena', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField()),
                ('motonave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_servicios', to='erp.motonave')),
            ],
        ),
    ]
