# Generated by Django 4.2.6 on 2024-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_remove_motonave_cantidad_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='cantidad_servicios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
