# Generated by Django 4.2.6 on 2024-04-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_motonave_cantidad_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaservicio',
            name='numero_viaje',
        ),
        migrations.AddField(
            model_name='motonave',
            name='numero_viaje',
            field=models.IntegerField(default=0),
        ),
    ]
