# Generated by Django 4.2.6 on 2024-04-24 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_fichaservicio_numero_viaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motonave',
            name='fecha_nominacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
