# Generated by Django 4.2.6 on 2024-04-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_motonave_fecha_nominacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motonave',
            old_name='cantidad_servicios',
            new_name='cantidad_serviciosHistorial',
        ),
        migrations.AddField(
            model_name='motonave',
            name='cantidad_serviciosActual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
