# Generated by Django 4.2.6 on 2024-04-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_rename_descripcion_motonave_comentarioactual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='conductor',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_licencia',
            field=models.CharField(blank=True, choices=[('', ''), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='personal',
            name='especialidades',
            field=models.ManyToManyField(to='erp.especialidad'),
        ),
    ]
