# Generated by Django 4.2.6 on 2024-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_especialidad_personal_conductor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('litros_ingreso', models.BigIntegerField()),
                ('numero_factura', models.BigIntegerField()),
                ('tipo_quimico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('numero_motor', models.CharField(max_length=100, unique=True)),
                ('numero_chasis', models.CharField(max_length=100, unique=True)),
                ('cilindrada', models.CharField(max_length=50)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('primer_ingreso', models.DateField()),
                ('patente', models.CharField(max_length=6, unique=True)),
                ('fecha_permiso_circulacion', models.DateField()),
                ('fecha_soap', models.DateField()),
                ('fecha_revision_tecnica', models.DateField()),
                ('seguro_nombre', models.CharField(max_length=100)),
                ('seguro_poliza', models.BigIntegerField()),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20)),
            ],
        ),
    ]
