# Generated by Django 4.2.6 on 2024-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_quimico_vario_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimico',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='vario',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('En Operación', 'En Operación')], default='Disponible', max_length=20),
        ),
    ]
